/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class GreetingAppTest {
    @Test void appHasAGreeting() {
        GreetingApp classUnderTest = new GreetingApp();
        assertNotNull(classUnderTest.sayHello("World"), "app should have a greeting");
    }
}