/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world;

import java.util.logging.Logger;

public class Greeting {

	private static final Logger logger = Logger.getLogger(Greeting.class.getName());

	public String getGreeting(String name) {
		logger.fine(name);
		return "Hello " + name + "!";
	}
}
