/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class GreetingTest {
	@Test
	void appHasAGreeting() {
		Greeting classUnderTest = new Greeting();
		assertNotNull(classUnderTest.getGreeting("World"), "app should have a greeting");
	}
}