/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world;

import java.util.logging.Level;
import java.util.logging.Logger;

public class GreetingApp {
    
    private static final Logger logger = Logger.getLogger(GreetingApp.class.getName());

    public String sayHello(String name)
    {
        return new Greeting().getGreeting(name);
    }

    @ExcludeFromJacocoGeneratedReport
    public static void main(String[] args) {
        logger.log(Level.INFO, "{0}", new GreetingApp().sayHello("World"));
    }
}
